# Generated by Django 4.1.1 on 2022-10-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Añadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('estreno', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
        migrations.DeleteModel(
            name='Series_Accion',
        ),
    ]
