# Generated by Django 4.1.1 on 2022-10-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0002_añadir_delete_comentarios_delete_generos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
